apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1000m
    defaultRequest:
      memory: 256Mi
      cpu: 500m
    type: Container
